spring:
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8180

wfd:
  menu:
    appetizers:
      url: http://wfdappetizer-service/appetizers
    entrees:
      url: http://wfdentree-service/entrees
    desserts:
      url: http://wfddessert-service/desserts

---
#spring:
#  profiles: cloud
#eureka:
#  instance:
#    nonSecurePort: 80
#    preferIpAddress: false
